# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-08 22:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='media/')),
                ('bio', models.CharField(blank=True, max_length=140)),
                ('movie_wish_list', models.TextField(default='[]')),
                ('music_wish_list', models.TextField(default='[]')),
                ('book_wish_list', models.TextField(default='[]')),
                ('movie_watched', models.TextField(default='[]')),
                ('music_listened', models.TextField(default='[]')),
                ('book_read', models.TextField(default='[]')),
                ('follower', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
