# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-27 00:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0001_initial'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='media/')),
                ('bio', models.CharField(blank=True, max_length=140)),
                ('movie_wish_list', models.TextField(blank=True)),
                ('music_wish_list', models.TextField(blank=True)),
                ('book_wish_list', models.TextField(blank=True)),
                ('movie_watched', models.TextField(blank=True)),
                ('music_listened', models.TextField(blank=True)),
                ('book_read', models.TextField(blank=True)),
                ('follower', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('liked_movie_comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_liker', to='movie.MovieComment')),
                ('liked_music_comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_liker', to='music.MusicComment')),
                ('movie_comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_commenter', to='movie.MovieComment')),
                ('music_comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_commenter', to='music.MusicComment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
