# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-27 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='writer',
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='writers',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='person',
            name='imdb_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
