# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-08 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='all_rates',
            field=models.DecimalField(decimal_places=1, max_digits=30),
        ),
        migrations.AlterField(
            model_name='moviecomment',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
